### ISSUE TITLE
Live preview?

### ISSUE THREAD

**Issue by jbmoelker** [jacobp100/react-isomophic-demo#1]
Very much enjoyed this demo and the related article. Took me some time to get it to run locally (due to latest JS syntax in api.js). So figured, just as a suggestion, a live preview would be a great addition. You could deploy the entire app on a (free) Heroku domain: https://www.heroku.com/nodejs

**Comment by griiettner** [comment]
@jbmoelker how did you fix the issue

```
/Users/XXXXX/Projects/react-isomophic-demo/api/index.js:4
const { filter, matches, uniqueId } = require('lodash/fp');
      ^

SyntaxError: Unexpected token {
```

I assume the error you had is the same... if you could give a hint, would be great...

Thanks

**Comment by griiettner** [comment]
ok... I found it... since my node is version before 6, this approach will not work... so I had to set my `const`like this...

```
const filter = require('lodash/fp');
const matches = require('lodash/fp');
const uniqueId = require('lodash/fp');
```

Hope this helps others as well...

**Comment by jacobp100** [comment]
Sorry, I never got around to doing this. The api works in node 6, but you can also `npm install -g babel-cli` and then `babel-node api`.

**Comment by jacobp100** [comment]
I’ve updated the readme.
